export const majors = [
  "Africana Studies",
  "Anthropology",
  "Applied Mathematics and Statistics",
  "Art History and Criticism",
  "Art Studio",
  "Asian and Asian American Studies",
  "Astronomy/Planetary Sciences",
  "Atmospheric and Oceanic Sciences",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Management",
  "Chemical and Molecular Engineering",
  "Chemistry",
  "Civil Engineering",
  "Climate Science",
  "Clinical Laboratory Sciences",
  "Coastal Environmental Studies",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Creative Writing",
  "Data Science",
  "Earth and Space Sciences",
  "Economics",
  "Ecosystems and Human Impact",
  "Electrical Engineering Online",
  "Electrical Engineering",
  "Engineering Chemistry",
  "Engineering Science",
  "English",
  "Environmental Design, Policy, and Planning",
  "Environmental Humanities",
  "Environmental Studies",
  "French",
  "Geology",
  "Globalization Studies and International Relations",
  "Health Science",
  "History",
  "Human Evolutionary Biology",
  "Information Systems",
  "Italian Studies",
  "Journalism",
  "Linguistics",
  "Marine Sciences",
  "Marine Vertebrate Biology",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Media/Art/Culture",
  "Multidisciplinary Studies",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Respiratory Care",
  "Rhetoric and Writing",
  "Social Work",
  "Sociology",
  "Spanish Language and Literature",
  "Sustainability Studies",
  "Technological Systems Management",
  "Women's and Gender Studies",
  //extra
  "Scientology"
];
