export const skills = [
    "3D Modeling",
    "Adobe Creative Suite",
    "CAD",
    "Data Analysis",
    "Figma",
    "Marketing",
    "Node.js",
    "Python",
    "React",
    "Research",
    "Social Media",
    "UI/UX",
    "Writing",
    "Project Management",
    "Public Speaking",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Communication",
    "Time Management",
    "Adaptability",
    "Microsoft Office Suite",
    "Google Workspace",
    "SQL",
    "JavaScript",
    "HTML/CSS",
    "Git/GitHub",
    "Cloud Computing",
    "Cybersecurity",
    "Machine Learning",
    "Artificial Intelligence",
    "Statistical Analysis",
    "Financial Modeling",
    "Business Intelligence",
    "SEO/SEM",
    "Video Editing",
    "Graphic Design",
    "Copywriting",
    "Customer Service",
    "Sales",
    "Negotiation",
    "Leadership",
    "Data Visualization",
    "Web Development",
    "Mobile App Development",
    "Network Administration",
    "Database Management",
    "Technical Support",
    "Agile Methodologies",
    "Risk Management",
    "Supply Chain Management",
    "Foreign Language Proficiency",
    // Africana Studies
    "Social Responsibility",
    "Cultural Engagement",
    "Social Justice Advocacy",
    "Intercultural Communication",
    // Anthropology
    "Record Keeping",
    "Analytical Reading",
    "Cross-cultural Adaptation",
    "Oral Expression",
    "Ethnographic Research",
    "Qualitative Data Collection",
    // Applied Math & Stats
    "Data Modeling",
    "Cryptography",
    "Big Data Management",
    "Data Clustering",
    "Mathematical Proof",
    "Numerical Analysis",
    "Algorithm Development",
    "Statistical Inference",
    // Art History
    "Visual Analysis",
    "Art Appraisal",
    "Arts Administration",
    "Art Conservation",
    "Archival Management",
    "Cultural Interpretation",
    "Comparative Analysis",
    "Historical Contextualization",
    // Studio Art
    "Drawing",
    "Painting",
    "Sculpting",
    "Printmaking",
    "Digital Art",
    "Portfolio Development",
    "Art Critique",
    "Material Knowledge",
    // Asian & Asian American Studies
    "Multidisciplinary Analysis",
    "Identity Analysis",
    "Civic Engagement",
    "Community Engagement",
    "Social Change Advocacy",
    "Cultural Competence",
    "Area Studies Research",
    // Astronomy/Planetary Sci.
    "Quantitative Analysis",
    "Scientific Programming",
    "Remote Sensing",
    "Telescope Operation",
    "Spacecraft Data Analysis",
    "Astronomical Observation",
    "Astrophysical Modeling",
    // Atmospheric & Oceanic Sci.
    "Atmospheric Modeling",
    "Weather Forecasting",
    "Climate Analysis",
    "Environmental Monitoring",
    "Geophysical Data Processing",
    "Oceanographic Analysis",
    "Scientific Computing",
    "Meteorological Data Analysis",
    // Business Management
    "Managerial Leadership",
    "Workflow Optimization",
    "Strategic Planning",
    "Resource Management",
    "Performance Monitoring",
    "Ethical Decision Making",
    "Financial Acumen",
    "Business Analytics",
    "Goal Setting",
    // Chemistry
    "Chemical Analysis",
    "Experimental Design",
    "Laboratory Techniques",
    "Chemical Synthesis",
    "Spectroscopy",
    "Chromatography",
    "Titration",
    "Material Characterization",
    // Climate Science
    "Climate Adaptation",
    "Mitigation Strategies",
    "Environmental Issue Identification",
    "Climate Modeling",
    "Carbon Accounting",
    "Policy Analysis",
    "Climate Data Interpretation",
    // Clinical Lab Sciences
    "Laboratory Testing",
    "Diagnostic Procedures",
    "Quality Control",
    "Specimen Analysis",
    "Medical Instrumentation",
    "Hematology",
    "Microbiology",
    "Immunohematology",
    "Urinalysis",
    // Coastal Environ. Studies
    "GIS Mapping",
    "Water Quality Testing",
    "Environmental Regulations Compliance",
    "Marine Ecology",
    "Coastal Zone Management",
    "Ocean Conservation",
    "Field Data Collection",
    "Environmental Remediation",
    // Communication
    "Media Relations",
    "Content Creation",
    "Public Relations",
    "Crisis Communication",
    "Interpersonal Communication",
    "Persuasion",
    "Digital Storytelling",
    "Campaign Development",
    // Creative Writing
    "Narrative Development",
    "Poetry Writing",
    "Screenwriting",
    "Playwriting",
    "Editing",
    "Proofreading",
    "Manuscript Preparation",
    "Literary Analysis",
    // Earth & Space Sciences
    "Geological Analysis",
    "Plenetary Geology",
    "Geophysics",
    "Space Exploration Knowledge",
    "Scientific Data Interpretation",
    "Paleontology",
    "Mineralogy",
    "Petrology",
    // Economics
    "Economic Modeling",
    "Econometrics",
    "Public Policy Analysis",
    "Market Analysis",
    "Microeconomics",
    "Macroeconomics",
    "Behavioral Economics",
    "Financial Forecasting",
    // Ecosystems & Human Impact
    "Ecosystem Analysis",
    "Environmental Impact Assessment",
    "Conservation Planning",
    "Sustainable Development",
    "Environmental Policy",
    "Ecological Restoration",
    "Biodiversity Conservation",
    "Resource Management",
    // English
    "Literary Criticism",
    "Rhetorical Analysis",
    "Genre Analysis",
    "Editorial Review",
    "Content Editing",
    "Stylistic Writing",
    "Persuasive Writing",
    "Argumentation",
    // Environmental Design
    "Landscape Design",
    "Urban Planning",
    "Architectural Design",
    "Sustainable Design",
    "Site Planning",
    "Permaculture Design",
    "Green Building Principles",
    "Environmental Aesthetics",
    // Environmental Humanities
    "Environmental Ethics",
    "Eco-criticism",
    "Cultural Ecology",
    "Human-Nature Relations",
    "Environmental Justice",
    "Community Organizing",
    "Narrative Analysis",
    "Interdisciplinary Synthesis",
    // Environmental Studies
    "Environmental Policy Analysis",
    "Conservation Science",
    "Renewable Energy Systems",
    "Waste Management",
    "Pollution Control",
    "Water Resource Management",
    "Environmental Education",
    "Sustainability Reporting",
    // French
    "French Language Proficiency",
    "Cross-Cultural Communication",
    "Translation",
    "Interpretation",
    "Francophone Culture",
    "Linguistic Analysis",
    // Geology
    "Mineral Identification",
    "Rock Classification",
    "Field Mapping",
    "Geological Surveying",
    "Plate Tectonics",
    "Geochronology",
    "Hydrogeology",
    "Structural Geology",
    // Globalization & Intl. Relations
    "International Relations Theory",
    "Geopolitics",
    "Diplomatic Protocol",
    "Global Governance",
    "Cross-Cultural Negotiation",
    "International Law",
    "Human Rights Advocacy",
    "Area Studies Research",
    // Health Science
    "Health Promotion",
    "Public Health Education",
    "Epidemiology",
    "Health Policy",
    "Patient Care Coordination",
    "Wellness Coaching",
    "Health Data Management",
    "Medical Terminology",
    // History
    "Archival Research",
    "Historiography",
    "Primary Source Analysis",
    "Historical Interpretation",
    "Chronological Reasoning",
    "Historical Narrative",
    "Oral History",
    "Genealogy",
    // Italian Studies
    "Italian Language Proficiency",
    "Italian Cultural Knowledge",
    "Italian Literature Analysis",
    "Romance Linguistics",
    "Art History (Italian Focus)",
    "Dialectology",
    // Journalism
    "News Reporting",
    "Feature Writing",
    "Investigative Journalism",
    "Interviewing Techniques",
    "Copy Editing",
    "Media Law",
    "Broadcast Journalism",
    "Digital Journalism",
    // Linguistics
    "Phonetics",
    "Phonology",
    "Syntax",
    "Semantics",
    "Morphology",
    "Sociolinguistics",
    "Psycholinguistics",
    "Language Documentation",
    // Marine Sciences
    "Oceanography",
    "Ichthyology",
    "Marine Conservation",
    "Oceanographic Instrumentation",
    "Underwater Surveying",
    "Coastal Ecology",
    "Fisheries Management",
    "Marine Policy",
    // Mass Communication
    "Media Production",
    "Public Opinion Analysis",
    "Media Ethics",
    "Audience Analysis",
    "Communication Campaigns",
    "Broadcast Media",
    "Film Production",
    "Digital Media Strategy",
    // Mathematics
    "Abstract Algebra",
    "Real Analysis",
    "Complex Analysis",
    "Topology",
    "Differential Equations",
    "Number Theory",
    "Discrete Mathematics",
    "Optimization",
    // Media/Art/Culture
    "Cultural Theory",
    "Media Literacy",
    "Visual Culture Analysis",
    "Performance Studies",
    "Digital Humanities",
    "Arts Curation",
    "Cultural Event Planning",
    "Media Criticism",
    // Multidisciplinary Studies
    "Interdisciplinary Research",
    "Synthesis of Knowledge",
    "Holistic Problem Solving",
    "Cross-Domain Application",
    "Adaptive Learning",
    "Systems Thinking",
    "Integrative Analysis",
    // Music
    "Instrumental Performance",
    "Vocal Performance",
    "Music Theory",
    "Composition",
    "Conducting",
    "Music Production",
    "Ethnomusicology",
    "Music History",
    // Nursing
    "Patient Assessment",
    "Medication Administration",
    "Wound Care",
    "Electronic Health Records",
    "Clinical Documentation",
    "Vital Signs Monitoring",
    "Patient Education",
    "Emergency Response",
    // Philosophy
    "Logical Reasoning",
    "Ethical Deliberation",
    "Metaphysical Inquiry",
    "Epistemological Analysis",
    "Existential Thought",
    "Argument Construction",
    "Conceptual Analysis",
    "Socratic Method",
    // Physics
    "Quantum Mechanics",
    "Thermodynamics",
    "Electromagnetism",
    "Classical Mechanics",
    "Particle Physics",
    "Astrophysics",
    "Experimental Physics",
    "Theoretical Physics",
    // Political Science
    "Political Analysis",
    "Policy Formulation",
    "Electoral Systems",
    "Public Administration",
    "Legislative Process",
    "Constitutional Law",
    "Political Campaigning",
    "Lobbying",
    // Psychology
    "Psychological Assessment",
    "Counseling Skills",
    "Cognitive Behavioral Therapy",
    "Developmental Psychology",
    "Social Psychology",
    "Abnormal Psychology",
    "Research Methods",
    "Psychometric Testing",
    // Respiratory Care
    "Respiratory Assessment",
    "Ventilator Management",
    "Airway Management",
    "Oxygen Therapy",
    "Pulmonary Function Testing",
    "Arterial Blood Gas Analysis",
    "Cardiopulmonary Resuscitation (CPR)",
    "Patient Monitoring",
    // Rhetoric and Writing
    "Persuasive Rhetoric",
    "Discourse Analysis",
    "Public Address",
    "Digital Rhetoric",
    "Visual Rhetoric",
    "Technical Documentation",
    "Audience Analysis (specific to rhetoric)",
    // Social Work
    "Caseload Management",
    "Crisis Intervention",
    "Client Advocacy",
    "Group Facilitation",
    "Community Development",
    "Social Policy Analysis",
    "Ethical Practice",
    "Case Planning",
    // Sociology
    "Sociological Theory",
    "Qualitative Research",
    "Quantitative Research",
    "Social Stratification Analysis",
    "Cultural Sociology",
    "Demography",
    "Urban Sociology",
    "Criminology",
    // Spanish Language & Lit.
    "Spanish Language Proficiency",
    "Hispanic Cultural Knowledge",
    "Spanish Literature Analysis",
    "Latin American Studies",
    "Iberian Studies",
    "Bilingualism",
    "Cultural Mediation",
    // Sustainability Studies
    "Sustainable Practices",
    "Environmental Stewardship",
    "Green Economy Principles",
    "Corporate Social Responsibility",
    "Renewable Energy Policy",
    "Ecological Footprint Analysis",
    "Circular Economy",
    "Life Cycle Assessment",
    // Women's & Gender Studies
    "Gender Analysis",
    "Feminist Theory",
    "Intersectionality",
    "LGBTQ+ Studies",
    "Critical Race Theory",
    "Power Dynamics Analysis",
    "Gender Policy",
    "Social Activism"
    
];